// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoBooth.Context;

#nullable disable

namespace PhotoBooth.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241122015417_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("PhotoBooth.Layout", b =>
                {
                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("PhotoBooth.LayoutPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AxisX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AxisY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LayoutId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LayoutPictures");
                });

            modelBuilder.Entity("PhotoBooth.LayoutThemes", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LayoutId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("LayoutThemes");
                });

            modelBuilder.Entity("PhotoBooth.Photo", b =>
                {
                    b.Property<string>("layoutId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("themeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
